### ISSUE TITLE
Add jgeoip to benchmark

### ISSUE THREAD

**Issue by rightaway** [runk/node-maxmind-benchmark#1]
On https://dev.maxmind.com/geoip/geoip2/downloadable/#MaxMind_APIs there's 4 NodeJS maxmind packages in addition to `maxmind`. This benchmark includes 3, could the fourth one be added as well? `jgeoip` at https://www.npmjs.com/package/jgeoip and https://github.com/jclo/jgeoip.

**Comment by runk** [comment]
Added.
